### ISSUE TITLE
UPD video streaming

### ISSUE THREAD

**Issue by tillnagel** [f41ardu/TelloProcessing#2]
Great little project!

Did you see Dan Shiffman's [UDP video streaming code](https://github.com/shiffman/Processing-UDP-Video-Streaming)? Might this work for using the stream from Tello in a desktop Processing sketch?

**Comment by f41ardu** [comment]
Sorry for my late replay. Yes I did and tried it already. But unfortunately it didn't work with Tello. I have noe clue why, so I've implemented my own code for testing.
